services:
  capitalreport:
    build:
      context: .
      dockerfile: Dockerfile.combined
    image: capitalreport:combined
    ports:
      - "8000:8000"
      - "4000:4000"
    volumes:
      # Mount the JSON file into the container
      - ./credentials.json:/app/credentials.json
    environment:
      # Point Google SDK to the file inside the container
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - GOOGLE_CLOUD_PROJECT=stable-smithy-270416
      - GOOGLE_CLOUD_LOCATION=us-central1
      - MONGO_URI=mongodb://mongo:27017/?directConnection=true
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
