import { test, expect, type Page } from '@playwright/test';
import {
    runSeeder,
    adminLogin,
    playerLogin,
    logout,
    selectLeague,
    loginAndSubmitScore,
    ALL_PLAYERS,
    adminSlotAndSaveRound,
    submitRemainingGroupScores
} from './helpers';

// ─── Credentials ──────────────────────────────────────────────────────────────
const ADMIN_EMAIL = 'test_pro@gmail.com';
const ADMIN_PASSWORD = 'Password@123';
const PLAYER_PASSWORD = 'Password@123';

// ─── Test ─────────────────────────────────────────────────────────────────────
test('Full league E2E: seed → slot round1 → score all matches → verify auto-slot round2', async ({ page }) => {

    // ══════════════════════════════════════════════════════════════════════════
    // STEP 1: Seed test data
    // ══════════════════════════════════════════════════════════════════════════
    console.log('\n━━━ STEP 1: Seeding test data ━━━');
    const leagueName = runSeeder();
    console.log('League name:', leagueName);

    // ══════════════════════════════════════════════════════════════════════════
    // STEP 2: Admin login → find league → go to slotting → save round 1
    // ══════════════════════════════════════════════════════════════════════════
    console.log('\n━━━ STEP 2: Admin slots Round 1 ━━━');

    await adminLogin(page, ADMIN_EMAIL, ADMIN_PASSWORD);

    // Click the league card on admin dashboard
    await page.waitForSelector('text=' + leagueName, { timeout: 15_000 });
    await page.locator('.interactive-card').filter({ hasText: leagueName }).click();
    await page.waitForURL('**/admin/league/**', { timeout: 15_000 });

    // Click "View and Slot"
    await page.locator('a:has-text("View and Slot")').click();
    await page.waitForURL('**/league/slotting**', { timeout: 15_000 });
    console.log('On slotting page:', page.url());

    // Generate Round 1 and save
    const groupPlayerEmails = await adminSlotAndSaveRound(page, "Slot Round 1");
    console.log('Slotting saved.');

    await logout(page);

    // ══════════════════════════════════════════════════════════════════════════
    // STEP 3: Player from Group 1 submits first match score
    // ══════════════════════════════════════════════════════════════════════════
    console.log('\n━━━ STEP 3: Group 1 — Player 1 submits score ━━━');
    const group1Players = groupPlayerEmails[0] ?? [];
    if (group1Players.length === 0) throw new Error('Group 1 has no players!');

    await loginAndSubmitScore(page, group1Players[0], PLAYER_PASSWORD, leagueName, 11, 5);
    console.log(`Score submitted by ${group1Players[0]}`);

    // ══════════════════════════════════════════════════════════════════════════
    // STEP 4: Remaining Group 1 players submit all remaining group 1 scores
    // ══════════════════════════════════════════════════════════════════════════
    console.log('\n━━━ STEP 4: Group 1 — remaining players submit scores ━━━');
    await submitRemainingGroupScores(page, group1Players, 1, leagueName, PLAYER_PASSWORD, /Round 1/i);

    // ══════════════════════════════════════════════════════════════════════════
    // STEP 5: Group 2 players submit all group 2 scores
    // ══════════════════════════════════════════════════════════════════════════

    console.log('\n━━━ STEP 5: Group 2 — all players submit scores ━━━');
    const group2Players = groupPlayerEmails[1] ?? [];
    if (group2Players.length === 0) throw new Error('Group 2 has no players!');
    await submitRemainingGroupScores(page, group2Players, 0, leagueName, PLAYER_PASSWORD, /Round 1/i);

    // ══════════════════════════════════════════════════════════════════════════
    // STEP 6: Verify Round 2 auto-slotting
    // ══════════════════════════════════════════════════════════════════════════
    console.log('\n━━━ STEP 6: Verify Round 2 auto-slotting ━━━');
    await adminLogin(page, ADMIN_EMAIL, ADMIN_PASSWORD);

    // Go to league details
    await page.waitForSelector('text=' + leagueName, { timeout: 15_000 });
    await page.locator('.interactive-card').filter({ hasText: leagueName }).click();
    await page.waitForURL('**/admin/league/**', { timeout: 15_000 });

    // Check that round 2 exists — the league-details page shows rounds
    // Navigate to the slotting page and verify currentRound is 2
    await page.locator('a:has-text("View and Slot")').click();
    await page.waitForURL('**/league/slotting**', { timeout: 15_000 });

    // The slotting page now displays all rounds. We expect Round 2 to be auto-generated by the backend and displayed.
    const r2Header = page.locator('h3').filter({ hasText: 'Round 2' });
    await expect(r2Header).toBeVisible({ timeout: 15_000 });

    // Done with step 4
    console.log('\n✅ E2E test passed — Group 1 Round 1 scores submitted!');
});



